# Week 1 Practice
Ujwal Joshi

In [2]:
import numpy as np

### Creating Arrays and Common Methods
The first way of creating a NumPy array is by converting your existing Python list.

In [3]:
python_list = [1, 2, 3, 4, 5]
print(python_list)
print(type(python_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [5]:
numpy_array = np.array(python_list)
print(numpy_array)
print(type(numpy_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
python_2d_array = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
print(python_2d_array)
print(type(python_2d_array))

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
<class 'list'>


In [7]:
numpy_2d_array = np.array(python_2d_array)
print(numpy_2d_array)
print(type(numpy_2d_array))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>


In [16]:
# My Modified Version
list_1 = [x for x in range(5)]
np_list_1 = np.array(list_1)
print(list_1, '\n', type(np_list_1))

list_2d = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
np_list_2d = np.array(list_2d)
print('\n', list_2d, '\n', type(np_list_2d))

[0, 1, 2, 3, 4] 
 <class 'numpy.ndarray'>

 [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]] 
 <class 'numpy.ndarray'>


However, you are more likely to use some of NumPy's built in methods to generate ndarrays. Here we'll introduce you to a few of these built in methods.

**arange(start, stop, step)** will return evenly spaced values within a given interval. The default step size is 1.

In [17]:
np.arange(0, 15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
np.arange(0, 15, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [29]:
# My Modified Version
print(np.arange(5, 10, 2))
print(np.arange(15, 10))

[5 7 9]
[]


What if we wanted a 2d array instead? We can call **reshape(rows, columns)** on an existing NumPy array. Please note that the product of rows and columns must evaluate to the total number of elements in your current NumPy array.

In [28]:
np.arange(0, 15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [41]:
# My Modified Version
np.arange(5, 16, 2).reshape(3, 2) #? 3 * 2 = 6, in total 6 elements from 1d

array([[ 5,  7],
       [ 9, 11],
       [13, 15]])

If we'd like to generate an ndarry of ***zeroes*** or ***ones*** (useful with certain calculations), we could do so by simply calling zeros or ones. For example:

In [43]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
np.zeros(15).reshape(3, 5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
np.ones(15).reshape(3, 5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
# My Modified Version
# np.zeros(-1)
np.zeros(12).reshape(2, 6)
np.ones(18).reshape(2, 9)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

You might have noticed that these values defaulted to floats. If for some reason you'd like to use a different type, say, int, you can insert an additional paramater such as ***dtype=int***. See more on dtypes [here](https://numpy.org/doc/stable/user/basics.types.html)

In [52]:
np.ones(15, dtype=int).reshape(3, 5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [55]:
# My Modified Version
np.ones(10, dtype=str).reshape(5, 2)

array([['1', '1'],
       ['1', '1'],
       ['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

A common matrix used in linear algebra is the identity matrix (an n × n square matrix with ones on the main diagonal and zeros elsewhere). We can generate this in NumPy using ***eye(n)***.

In [56]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
# My Modified Version
np.eye(10, dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

Another common use case is to generate an ndarray of random numbers. This can be done in 2 ways. ***rand*** (which will fill the ndarray with random samples from a uniform distribution over [0, 1)), and ***randn*** (which will return a sample (or samples) from the standard normal distribution.) Additionally, we can use ***randint(low, high, size)*** to generate a single or multiple random integers between [low, high). The size parameter specifies how many we'd like. Let's see a few examples.

In [58]:
np.random.rand(5) #? Uniform Distribution

array([0.12901354, 0.62754067, 0.74036455, 0.48614094, 0.28572351])

In [61]:
np.random.randn(5) #? Normal Distribution

array([-2.23469978,  0.71577942, -0.84509503, -0.72506322,  0.37057277])

In [64]:
np.random.randint(1,100)

77

In [65]:
np.random.randint(1, 100, 15)

array([77,  1, 64, 40, 41, 80, 78, 16, 45,  8, 30,  9, 90, 84, 72])

In [66]:
# My Modified Version
np.random.randint(1, 100, 15).reshape(3, 5)

array([[67, 39, 79,  5, 20],
       [71, 79, 82, 13, 20],
       [40, 14, 65, 50,  9]])

Other common methods that you're likely to encounter in this class include ***min, max, argmin***, and ***argmax***. The only difference between the two arg methods is that they'll instead return the index position of the min/max value. For example:

In [67]:
A = np.random.randint(0, 100, 20).reshape(4, 5)
A

array([[75, 51, 87, 76,  4],
       [42, 80, 78, 38, 88],
       [63, 78, 81, 83, 37],
       [30, 35, 56, 29, 97]])

In [68]:
print(f'The smallest value in A is {A.min()}, and is a located at position {A.argmin()}')
print(f'The largest value in A is {A.max()}, and is a located at position {A.argmax()}')

The smallest value in A is 4, and is a located at position 4
The largest value in A is 97, and is a located at position 19


Lastly, we'll often find ourselves wanting to know the shape (dimensions) of our ndarray. This can be done using ***shape***.

In [69]:
A.shape

(4, 5)

In [70]:
np.shape(A)

(4, 5)

Great! you now know how to create NumPy arrays and some of the common methods. Let's now look into some common operations we can perform on these arrays.

### Common Operations

In [71]:
A = np.arange(1, 16)
B = np.arange(1, 30, 2)
C = np.arange(0, 4).reshape(2, 2)
D = np.arange(0, 4).reshape(2, 2)
E = np.arange(1, 16).reshape(3, 5)
F = np.arange(11)
print(f'A: {A}')
print(f'B: {B}')
print('C:')
print(C)
print('D:')
print(D)
print('E:')
print(E)
print(f'F: {F}')

A: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
B: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
C:
[[0 1]
 [2 3]]
D:
[[0 1]
 [2 3]]
E:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
F: [ 0  1  2  3  4  5  6  7  8  9 10]


#### Arithmetic

In [78]:
A + B

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44])

In [76]:
# My Modified Version
C + D

array([[0, 2],
       [4, 6]])

In [77]:
A + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [85]:
# My Modified Version
A + (2e2)

array([201., 202., 203., 204., 205., 206., 207., 208., 209., 210., 211.,
       212., 213., 214., 215.])

In [79]:
A - 5

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
# My Modified Version
A - (-1)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [80]:
A * B

array([  1,   6,  15,  28,  45,  66,  91, 120, 153, 190, 231, 276, 325,
       378, 435])

In [87]:
# My Modified Version
A * -B

array([  -1,   -6,  -15,  -28,  -45,  -66,  -91, -120, -153, -190, -231,
       -276, -325, -378, -435])

In [81]:
A * 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

In [88]:
# My Modified Version
A * 1e2

array([ 100.,  200.,  300.,  400.,  500.,  600.,  700.,  800.,  900.,
       1000., 1100., 1200., 1300., 1400., 1500.])

In [82]:
A / B

array([1.        , 0.66666667, 0.6       , 0.57142857, 0.55555556,
       0.54545455, 0.53846154, 0.53333333, 0.52941176, 0.52631579,
       0.52380952, 0.52173913, 0.52      , 0.51851852, 0.51724138])

In [92]:
# My Modified Version
A / -B

array([-1.        , -0.66666667, -0.6       , -0.57142857, -0.55555556,
       -0.54545455, -0.53846154, -0.53333333, -0.52941176, -0.52631579,
       -0.52380952, -0.52173913, -0.52      , -0.51851852, -0.51724138])

In [83]:
A / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5])

In [93]:
# My Modified Version
A / (B / 2)

array([2.        , 1.33333333, 1.2       , 1.14285714, 1.11111111,
       1.09090909, 1.07692308, 1.06666667, 1.05882353, 1.05263158,
       1.04761905, 1.04347826, 1.04      , 1.03703704, 1.03448276])

Note: Be careful dividing by zero. You'll get ***nan*** short for Not a number.

As you may have noticed, the standard operations *, +, -, / work element-wise on arrays. If you'd like to instead do matrix multiplication, ***matmul*** can be used. Here's a quick reference in case you forgot how matrix multiplication works.

In [84]:
np.matmul(C, D)

array([[ 2,  3],
       [ 6, 11]])

In [94]:
# My Modified Version
np.matmul(D, C)

array([[ 2,  3],
       [ 6, 11]])

#### Universal Functions
NumPy also contains [universal functions](https://numpy.org/doc/stable/reference/ufuncs.html), which is a function that operates on ndarrays in an element-by-element fashion. Let's see a few examples.

In [95]:
np.sqrt(E)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [102]:
# My Modified Version
np.sqrt(E) / E

array([[1.        , 0.70710678, 0.57735027, 0.5       , 0.4472136 ],
       [0.40824829, 0.37796447, 0.35355339, 0.33333333, 0.31622777],
       [0.30151134, 0.28867513, 0.2773501 , 0.26726124, 0.25819889]])

In [96]:
np.log(E)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [109]:
# My Modified Version
np.log(A)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ])

Something that will often come in handy is the ***where(condition, x, y)*** method. This will loop through every element in your ndarray and return a new ndarray that replaces the element with x if the condition is met, and y if the condition is not met. In the example below we're multiplying all odd numbers by 100, else replacing with -1. Try changing the -1 to F in the example below and see what happens.

In [98]:
np.where(F%2==0, -1, F*100)

array([ -1, 100,  -1, 300,  -1, 500,  -1, 700,  -1, 900,  -1])

In [100]:
# My Modified Version
np.where(F%2==0, 0, F*100) #? Similar to using lambda with map function in python, or the map array method in js

array([  0, 100,   0, 300,   0, 500,   0, 700,   0, 900,   0])

Nice! Now that you know how to create NumPy arrays and perform basic operations on them, let's take a look at how to index and select certain elements.

### Indexing
#### Indexing 1d array
Note: recall that counting starts from 0. Given an array [5, 6, 7, 8], we say that value 5 is at index/position 0.

In [110]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Obtaining a single element will look similar to Python arrays:

In [111]:
print(f'A[0]: {A[0]}')
print(f'A[5]: {A[5]}')
print(f'A[14]: {A[14]}')

A[0]: 0
A[5]: 5
A[14]: 14


We can grab a section using ***A[start_index : stop_index]***. stop_index is not inclusive.

In [112]:
A[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

We can also modify values in this way:

In [113]:
A[0:10] = 500
A

array([500, 500, 500, 500, 500, 500, 500, 500, 500, 500,  10,  11,  12,
        13,  14])

In [118]:
# My Modified Version
A[11:14] = np.sqrt(A[11:14])
A

array([500, 500, 500, 500, 500, 500, 500, 500, 500, 500,  10,   0,   0,
         0,  14])

#### Indexing a 2d array

In [119]:
B = np.arange(50).reshape(5, 10)
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [120]:
print(f'0th row and 2nd col in B: {B[0, 2]}')
print(f'3rd row and 3rd col in B: {B[3, 3]}')
print(f'4th row and 2nd col in B: {B[4, 2]}')

0th row and 2nd col in B: 2
3rd row and 3rd col in B: 33
4th row and 2nd col in B: 42


Similar to before, we can also grab a section of interest from this 2darray. Only now we have to specify both the row sections of interest and column sections of interest. ***B[0:2, 3:5]*** says: I want rows 0-2 from B, but only the elements in that row corresponding to columns 3-5. Recall that stop_index is not inclusive. Here stop_index for the rows is 2, and stop_index for the columns is 5.

In [121]:
B[0:2, 3:5]

array([[ 3,  4],
       [13, 14]])

Again, we can also modify values in this way.

In [122]:
B[0:2, 3:5] = -1
B

array([[ 0,  1,  2, -1, -1,  5,  6,  7,  8,  9],
       [10, 11, 12, -1, -1, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [125]:
# My Modified Version
B[0:2, 3:6] = np.square(B[0:2, 3:6])
B

array([[  0,   1,   2,   1,   1,  25,   6,   7,   8,   9],
       [ 10,  11,  12,   1,   1, 225,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

#### Boolean Array Indexing

In [126]:
C = np.arange(50).reshape(10, 5)
C

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

A really cool feature of NumPy is that we can index arrays using comparison operators. This Lets us modify or select only elements meeting some condition. To demonstrate this, lets first see what is returned when we try to use comparison operators with our arrays.

In [127]:
C%2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

We get back an array of the same shape telling us which values in ***C*** satisfy the condition `C%2==0` (even values). Recall that 0 is an alias for False, and 1 is an alias for True. Because of this, we can actually call the sum function right off of this array, which will evaluate to the total number of even numbers in ***C***.

In [128]:
(C%2 == 0).sum()

25

Something we'll find ourselves doing more often is passing the boolean array as an index. What this will do is filter out the False elements and only leave us with the elements corresponding to True (even values in our case).

In [129]:
C[C%2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [130]:
# My Modified Version
C[C%2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

Congratulations! You now know how to create NumPy arrays, perform common operations on them, and how to index them. There's so much that NumPy can do, but this should cover just about all that you'll need to succeed in this course. Other popular Python libraries used for data science such as Pandas and Matplotlib are built on top of NumPy, so you'll be using a lot of these features alongside those libraries.